#include <stdio.h>
#include <math.h>

#define		ANGLE_INCREMENT		0.25
#define		LENGTH_PROCESSOR	40
#define		AMPLITUDE_PROCESSOR	9
#define	TOP_X_PROCESSOR	WINDOW_WIDTH - LENGTH_PROCESSOR - WINDOW_BORDER - 40
#define		TOP_Y_PROCESSOR		4
#define		PI			03.141592654

#define		DISTANCE_CLICK_BUTTON	3
#define		RADIUS_BUTTON		8
#define		CENTER_BUTTON_X		(TOP_X_PROCESSOR + LENGTH_PROCESSOR + 20)
#define		CENTER_BUTTON_Y		(TOP_Y_PROCESSOR + AMPLITUDE_PROCESSOR)
