#define		X_DIVISIONS_ATTR	3
#define		Y_DIVISIONS_ATTR	14

#define		X_SEP_ATTR	166 /*(MENU_WINDOW_WIDTH / X_DIVISIONS_ATTR*/
#define		Y_SEP_ATTR	20  /*(MENU_WINDOW_HEIGHT / Y_DIVISIONS_ATTR*/

#define		LOOP_COUNTER		100000

#define		BEGIN_Y_ATTR_TEXT	4
