#include "xx.h"

#define		HALF_WAY_Y		(SLID_WINDOW_HEIGHT / 2)
#define		UPPER_QUARTER_Y		(HALF_WAY_Y / 2)
#define		LOWER_QUARTER_Y		(HALF_WAY_Y + UPPER_QUARTER_Y)

#define		HALF_WAY_X_1		0
#define		HALF_WAY_X_2		SLID_WINDOW_WIDTH

#define		FULL_LENGHT		SLID_WINDOW_HEIGHT

#define		SLIDER_BUTTON_WIDTH	(SLID_WINDOW_WIDTH - 2)
#define		SLIDER_BUTTON_HEIGHT	41
